version: 0.2

phases: 
 build:
  commands:
   - echo Entered build phase
   - mvn install
 post_build:
  commands:
   - echo Build completed successfully

artifacts:
 files: 
  -target/aswcicd.jar
 discard-paths: yes
